version: '3.9'

services:
  #MongoDB service
  employee_mongo_db:
    container_name: employee_database
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  #employee API service
  employee_api:
    container_name: employee_api
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      MONGO_URI: mongodb://employee_mongo_db:27017
      DB_NAME: employee_ms
      NODE_ENV: development
    depends_on:
      - employee_mongo_db

volumes:
  mongo_db: {}